In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/juarezefren/datasets/main/Iris.csv')
df.shape

(150, 6)

In [ ]:
df.head(5)
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df.drop(['Id'],axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#df["Species"] = le.fit_transform(df["Species"])
#df.head()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
X = df.iloc[:,:-1]
X.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [ ]:
y = df.iloc[:,-1]
y.head(5)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [ ]:
X.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaled_x = scaler.fit_transform(X)
X = pd.DataFrame(scaled_x, columns=X.columns)
X.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.900681      1.032057      -1.341272     -1.312977
1      -1.143017     -0.124958      -1.341272     -1.312977
2      -1.385353      0.337848      -1.398138     -1.312977
3      -1.506521      0.106445      -1.284407     -1.312977
4      -1.021849      1.263460      -1.341272     -1.312977

In [ ]:
X.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   1.500000e+02  1.500000e+02   1.500000e+02  1.500000e+02
mean   -4.736952e-16 -6.631732e-16   3.315866e-16 -2.842171e-16
std     1.003350e+00  1.003350e+00   1.003350e+00  1.003350e+00
min    -1.870024e+00 -2.438987e+00  -1.568735e+00 -1.444450e+00
25%    -9.006812e-01 -5.877635e-01  -1.227541e+00 -1.181504e+00
50%    -5.250608e-02 -1.249576e-01   3.362659e-01  1.332259e-01
75%     6.745011e-01  5.692513e-01   7.627586e-01  7.905908e-01
max     2.492019e+00  3.114684e+00   1.786341e+00  1.710902e+00

In [ ]:
from sklearn.neural_network import MLPClassifier

modelo = MLPClassifier(hidden_layer_sizes = (16,40,12), max_iter=800, activation = 'relu', solver = 'adam')

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(modelo, X, y,
                         scoring="accuracy",
                         cv=5, n_jobs=-1)
print(scores)
print(scores.mean())

[0.96666667 0.96666667 0.96666667 0.93333333 0.96666667]
0.96


In [ ]:
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score

x_train, x_test, y_train, y_test = tts(X,y, test_size=0.2)
modelo.fit(x_train,y_train)
y_pred= modelo.predict(x_test)
accuracy_score(y_test,y_pred)

0.9666666666666667

In [ ]:
from sklearn.metrics import confusion_matrix
C=confusion_matrix(y_pred, y_test)
print(C)



[[11  0  0]
 [ 0  9  0]
 [ 0  1  9]]
